version: '3'

services:
  # database POSTGRES
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  # OUR APP
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - db

  # REDIS
  redis:
    image: redis
    ports:
      - '6379:6379'

